<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'DATABASE_URL' => 'mysql://b5f415e99c2cda:cf8dcade@us-cdbr-east-06.cleardb.net/heroku_f80efddce1ba421?reconnect=true',
  'HTTPS' => 'on',
  'APP_SECRET' => 'ab1a4678cc5c296c0247299548585b8f',
);
